services:
  backend:
    build:
      context: .
      dockerfile: /docker/Dockerfile.backend
    ports:
      - 8000:8000
  websocket:
    build:
      context: .
      dockerfile: /docker/Dockerfile.websocket
    ports:
      - 8081:8081
  web:
    build:
      context: .
      dockerfile: /docker/Dockerfile.web
    ports:
      - 3000:3000
