FROM oven/bun:alpine AS base

WORKDIR /app
ARG DATABASE_URL

COPY /packages ./packages
COPY ./bun.lock ./

COPY ./package.json ./
COPY ./turbo.json ./

COPY ./apps/backend ./apps/backend
RUN echo "DATABASE_URL=\"${DATABASE_URL}\"" > ./packages/database/.env



RUN bun install
RUN bun run generate:db

CMD ["bun","run","start:backend"]





# FROM base AS runner

# WORKDIR /app

# COPY --from=base /app/apps/backend/dist .

# EXPOSE 8000

# CMD bun index.js







