name: Deploy the backend
on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/next_mono_backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # Deploy to an VM
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/next_mono_backend:${{ github.sha }}
            docker stop next_mono_backend
            docker rm next_mono_backend
            docker run -d -e DATABASE_URL=${{ secrets.DATABASE_URL }} --name next_mono_backend -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/next_mono_backend:${{ github.sha }}
